### PR TITLE
Merge changes from LibXPUInfo

### PR DESCRIPTION
**Pull request by elpalmer**
* Cross-platform enhancements
* Clean build with MSVC x64 /W4 /WX

### CODE REVIEW

**Comment by MarissaDuBois-Intel** [comment]
Hi @elpalmer I made a change so I could compile on windows, can you verify that my change is ok before I merge?

**Comment by elpalmer** [comment]
> Hi @elpalmer I made a change so I could compile on windows, can you verify that my change is ok before I merge?

HI @MarissaDuBois-Intel , that change defeats the purpose of my change to make it build with /WX /W4 as required by SDL.  I think I see the issue, though, and I will push another change for you to try.

**Comment by elpalmer** [comment]
@MarissaDuBois-Intel Please review latest change.

**Comment by MarissaDuBois-Intel** [comment]
Code changes reviewed, tested, and approved.

**Pull request merged**
